# acl.auth.php
# <?php exit()?>
# Don't modify the lines above
#
# Access Control Lists
#
# Auto-generated by install script
# Date: Mon, 12 Dec 2011 01:50:20 +0000
*	@ALL	1
*	@user	8
private:*	@ALL	0
private:*	@user	8
